language: elixir
sudo: false

branches:
  only:
    - master
    - development

elixir:
  - 1.5.1
otp_release:
  - 19.1
  - 19.2
  - 20.0

matrix:
  include:
    - elixir: 1.4.0
      otp_release: 19.1
    - elixir: 1.4.0
      otp_release: 19.2
    - elixir: 1.4.1
      otp_release: 19.2
    - elixir: 1.4.2
      otp_release: 19.2
    - elixir: 1.4.3
      otp_release: 19.2
    - elixir: 1.4.4
      otp_release: 19.2
    - elixir: 1.5.0
      otp_release: 19.2
    - elixir: 1.5.0
      otp_release: 20.0
